import { useEffect, useState, type CSSProperties } from 'react'
import { ArrowDown, ArrowUpRight, BriefcaseBusiness, Code2, Menu, X } from 'lucide-react'
import { copy, portfolioData, type Language } from './i18n'
import { careerContent } from './careerData'
import { projectsData } from './projectsData'
import TechIcon from './TechIcon'
import './language.css'
import './visual-polish.css'
import './section-accents.css'
import './career-timeline.css'
import './project-links.css'
import './human-profile.css'

function SectionLabel({ index, children }: { index: string; children: string }) { return <div className="section-label"><span>{index}</span><span>{children}</span></div> }
function getInitialLanguage(): Language { return localStorage.getItem('indtec-language') === 'en' ? 'en' : 'pt' }
const technologyAccents: Record<string, string> = { 'C#':'154, 91, 225','.NET':'81, 43, 212','ASP.NET Core':'120, 76, 220',REST:'76, 201, 240',SQS:'255, 153, 0',SNS:'220, 74, 154',RabbitMQ:'255, 102, 0',Redis:'220, 56, 45','AWS Lambda':'255, 153, 0',Docker:'36, 150, 237',EKS:'50, 108, 229',CloudFormation:'139, 184, 46','SQL Server':'204, 41, 39',PostgreSQL:'51, 103, 145',DynamoDB:'64, 126, 201',Datadog:'99, 44, 166',FIX:'93, 225, 190',WCF:'132, 99, 222',SignalR:'116, 72, 187',SAP:'0, 157, 224',Architecture:'93, 225, 190','Code Review':'86, 157, 255',Mentoring:'177, 111, 255','Incident Response':'255, 102, 92' }
function technologyStyle(technology: string) { return { '--tech-accent': technologyAccents[technology] ?? '140, 150, 160' } as CSSProperties }
function AccentTitle({ children, accent }: { children: string; accent: string }) { const position=children.toLowerCase().indexOf(accent.toLowerCase()); if(position<0)return <>{children}</>; return <>{children.slice(0,position)}<span className="text-accent">{children.slice(position,position+accent.length)}</span>{children.slice(position+accent.length)}</> }

export default function App() {
  const [menuOpen,setMenuOpen]=useState(false); const [language,setLanguage]=useState<Language>(getInitialLanguage)
  const t=copy[language]; const baseData=portfolioData[language]; const data={...baseData,projects:projectsData[language]}; const career=careerContent[language]
  useEffect(()=>{localStorage.setItem('indtec-language',language);document.documentElement.lang=language==='pt'?'pt-BR':'en'},[language])
  const changeLanguage=(next:Language)=>{setLanguage(next);setMenuOpen(false)}
  const heroAccent=language==='pt'?'confiável':'reliable'; const systemsAccent=language==='pt'?'problema real':'real problem'
  const human = language === 'pt' ? { placeholder:'FOTO / PENDENTE', role:'SOFTWARE ENGINEER', location:'SP / BRASIL', status:'HUMAN / ONLINE', note:'Gosto de construir coisas novas. Mas acredito que manter, simplificar e evoluir o que já existe é parte igualmente importante da engenharia.', signals:['SOFTWARE','MÚSICA','INSTRUMENTOS','SISTEMAS DISTRIBUÍDOS','ESPAÇO'] } : { placeholder:'PHOTO / PENDING', role:'SOFTWARE ENGINEER', location:'SP / BRAZIL', status:'HUMAN / ONLINE', note:'I like building new things. But I believe maintaining, simplifying and evolving what already exists is an equally important part of engineering.', signals:['SOFTWARE','MUSIC','INSTRUMENTS','DISTRIBUTED SYSTEMS','SPACE'] }
  const portfolioProject = language === 'pt' ? { mission:'INDTEC / PUBLIC 001',status:'ATIVO',name:'Indtec Portfolio',description:'O próprio portfólio como produto público: conteúdo bilíngue, identidade visual técnica e evolução guiada por contexto, revisão humana e desenvolvimento assistido por IA.',stack:['React','TypeScript','Vite','AI-assisted'],source:'Código fonte' } : { mission:'INDTEC / PUBLIC 001',status:'ACTIVE',name:'Indtec Portfolio',description:'The portfolio itself as a public product: bilingual content, a technical visual identity and an evolution driven by context, human review and AI-assisted development.',stack:['React','TypeScript','Vite','AI-assisted'],source:'Source code' }

  return <div className="site-shell">
    <header className="site-header"><a className="brand" href="#top" aria-label="Indtec home"><span className="brand-mark">I</span><span>INDTEC</span></a><nav className="desktop-nav" aria-label="Primary navigation">{t.nav.map(([label,href])=><a href={href} key={href}>{label}</a>)}</nav><div className="header-actions"><div className="language-switch" aria-label="Language selector"><button className={language==='pt'?'is-active':''} onClick={()=>changeLanguage('pt')}>PT</button><span>/</span><button className={language==='en'?'is-active':''} onClick={()=>changeLanguage('en')}>EN</button></div><div className="header-meta"><span className="status-dot"/><span>{t.status}</span></div></div><button className="menu-button" onClick={()=>setMenuOpen(v=>!v)} aria-label="Toggle menu">{menuOpen?<X size={18}/>:<Menu size={18}/>}</button></header>
    {menuOpen&&<nav className="mobile-nav" aria-label="Mobile navigation"><div className="mobile-language"><button className={language==='pt'?'is-active':''} onClick={()=>changeLanguage('pt')}>PT</button><span>/</span><button className={language==='en'?'is-active':''} onClick={()=>changeLanguage('en')}>EN</button></div>{t.nav.map(([label,href],index)=><a href={href} key={href} onClick={()=>setMenuOpen(false)}><span>0{index+1}</span>{label}</a>)}</nav>}
    <main id="top">
      <section className="hero" id="profile"><div className="hero-grid" aria-hidden="true"/><div className="hero-kicker"><span>{t.heroKicker}</span><span>BR / 2026</span></div><div className="hero-copy"><p className="mono eyebrow">{t.heroEyebrow}</p><h1><AccentTitle accent={heroAccent}>{t.heroTitle}</AccentTitle><span>{t.heroTitleMuted}</span></h1><p className="hero-description">{t.heroDescription}</p></div><div className="hero-footer"><div className="hero-stack mono"><span>.NET</span><i/><span>AWS</span><i/><span>DISTRIBUTED SYSTEMS</span></div><a className="explore-link" href="#journey">{t.explore}<ArrowDown size={16}/></a></div></section>
      <section className="section about-section"><SectionLabel index="00 / PROFILE">{t.profileLabel}</SectionLabel><div className="human-profile-grid"><div className="profile-portrait" aria-label={human.placeholder}><div className="portrait-scan" aria-hidden="true"/><div className="portrait-placeholder"><div className="portrait-placeholder-mark" aria-hidden="true"/><p className="mono">{human.placeholder}</p></div><div className="portrait-meta mono"><span>{human.role}<br/>{human.location}</span><span>{human.status}</span></div></div><div className="human-profile-copy"><div className="statement-grid"><p className="statement-lead">{t.profileLead}</p><div className="statement-copy"><p>{t.profileP1}</p><p>{t.profileP2}</p></div></div><div className="human-note"><p>{human.note}</p></div><div className="human-signals mono">{human.signals.map(signal=><span key={signal}>{signal}</span>)}</div></div></div></section>
      <section className="section career-section" id="journey"><SectionLabel index="01 / FLIGHT LOG">{career.journeyLabel}</SectionLabel><div className="career-intro"><div><p className="mono eyebrow">{career.journeyEyebrow}</p><h2><AccentTitle accent={language==='pt'?'código':'code'}>{career.journeyTitle}</AccentTitle></h2></div><p>{career.journeyDescription}</p></div><div className="career-layout"><div className="timeline" aria-label={career.journeyLabel}>{career.career.map((item,index)=><article className={`timeline-item ${index===0?'is-current':''}`} key={`${item.company}-${item.period}`}><div className="timeline-rail" aria-hidden="true"><span className="timeline-node"/></div><div className="timeline-period mono">{item.period}<span>{item.duration}</span></div><div className="timeline-content"><div className="timeline-heading"><div><p className="mono eyebrow">{item.company}</p><h3>{item.role}</h3></div>{index===0&&<span className="current-badge mono">{career.current}</span>}</div><p>{item.focus}</p></div></article>)}</div><aside className="education-panel"><p className="mono eyebrow">{career.educationLabel}</p><div className="degree"><span className="degree-year mono">2018 — 2022</span><h3>{career.education.degree}</h3><p>{career.education.school}</p></div><div className="learning"><p className="mono eyebrow">{career.learningLabel}</p><div className="learning-list">{career.education.learning.map((item,index)=><span className="learning-pill mono" key={item}><i>{String(index+1).padStart(2,'0')}</i>{item}</span>)}</div></div></aside></div></section>
      <section className="section experience-section" id="experience"><SectionLabel index="02 / EXPERIENCE">{t.experienceLabel}</SectionLabel><div className="experience-list">{data.experience.map(item=><article className="experience-row" key={item.index}><div className="experience-index mono">{item.index}</div><div className="experience-body"><p className="mono eyebrow">{item.eyebrow}</p><h2>{item.title}</h2><p>{item.description}</p><div className="tag-row">{item.tags.map(tag=><span key={tag}>{tag}</span>)}</div></div></article>)}</div></section>
      <section className="section systems-section" id="systems"><SectionLabel index="03 / SYSTEMS">{t.systemsLabel}</SectionLabel><div className="systems-intro"><h2><AccentTitle accent={systemsAccent}>{t.systemsTitle}</AccentTitle></h2><p>{t.systemsDescription}</p></div><div className="capability-grid">{data.capabilities.map((capability,index)=><article className={`capability-card capability-card--${index+1}`} key={capability.id}><div className="card-top mono"><span>{capability.id}</span><span>{t.active}</span></div><TechIcon id={capability.id}/><h3>{capability.title}</h3><p>{capability.description}</p><div className="technology-list mono">{capability.technologies.map(technology=><span className="technology-pill" style={technologyStyle(technology)} key={technology}>{technology}</span>)}</div></article>)}</div></section>
      <section className="section projects-section" id="projects"><SectionLabel index="04 / MISSIONS">{t.projectsLabel}</SectionLabel><div className="projects-heading"><h2>{t.projectsTitle.split('\n').map((line,index)=><span className={`title-line ${index===1?'text-accent':''}`} key={line}>{line}{index===0&&<br/>}</span>)}</h2><p>{t.projectsDescription}</p></div><div className="project-list"><article className="project-row project-row--featured"><div className="project-mission mono"><span>{portfolioProject.mission}</span><span className="project-status">{portfolioProject.status}</span></div><div className="project-main"><h3>{portfolioProject.name}</h3><p>{portfolioProject.description}</p><div className="tag-row">{portfolioProject.stack.map(item=><span key={item}>{item}</span>)}</div><a className="project-source mono" href="https://github.com/fogacafe/indtec-portifolio" target="_blank" rel="noreferrer"><Code2 size={15}/>{portfolioProject.source}<ArrowUpRight size={14}/></a></div><a className="project-action" href="https://github.com/fogacafe/indtec-portifolio" target="_blank" rel="noreferrer" aria-label="Indtec Portfolio GitHub"><ArrowUpRight size={22}/></a></article>{data.projects.map(project=><article className="project-row" key={project.mission}><div className="project-mission mono"><span>INDTEC / {project.mission}</span><span className="project-status">{project.status}</span></div><div className="project-main"><h3>{project.name}</h3><p>{project.description}</p><div className="tag-row">{project.stack.map(item=><span key={item}>{item}</span>)}</div><div className="project-links">{project.demoHref&&<a className="project-source project-demo mono" href={project.demoHref}>{language==='pt'?'Abrir lab':'Open lab'}<ArrowUpRight size={14}/></a>}<a className="project-source mono" href={project.href} target="_blank" rel="noreferrer"><Code2 size={15}/>{language==='pt'?'Código fonte':'Source code'}<ArrowUpRight size={14}/></a></div></div><a className="project-action" href={project.demoHref??project.href} target={project.demoHref?undefined:'_blank'} rel={project.demoHref?undefined:'noreferrer'} aria-label={project.demoHref?`${project.name} live lab`:`${project.name} GitHub`}><ArrowUpRight size={22}/></a></article>)}</div></section>
      <section className="section principles-section"><SectionLabel index="05 / PRINCIPLES">{t.principlesLabel}</SectionLabel><div className="principles-grid">{data.principles.map(([index,title,text])=><article className="principle" key={index}><span className="mono">{index}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section className="contact-section" id="contact"><p className="mono eyebrow">{t.contactEyebrow}</p><h2>{t.contactTitle}</h2><p>{t.contactDescription}</p><div className="contact-links"><a className="primary-link" href="https://github.com/fogacafe" target="_blank" rel="noreferrer"><Code2 size={18}/> GitHub / fogacafe <ArrowUpRight size={17}/></a><a className="secondary-link" href="https://br.linkedin.com/in/fogacafe" target="_blank" rel="noreferrer"><BriefcaseBusiness size={18}/> LinkedIn / fogacafe <ArrowUpRight size={17}/></a></div></section>
    </main><footer className="site-footer mono"><span>{t.footer}</span><span>SYS.STATUS / NOMINAL</span><span>© 2026</span></footer>
  </div>
}
